name: PHP Build and Test

on:
  push:
    branches:
      - main  # Ou substitua pela branch desejada

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # Substitua pela versão desejada
        
    - name: Install Composer dependencies
      run: 
        composer install  # Instala as dependências do Composer
        